### ISSUE TITLE
can you provide whole scripts from you paper

### ISSUE THREAD

**Issue by conversodinHXL** [brookehjelm/Splice-Break#1]
as metioned as title, please.

**Comment by brookehjelm** [comment]
We are working on an updated version that will have more functionality and can do batch processing, pre-alignment, MapSplice alignment, automated filtering and annotation, so you may want to wait for that (feel free to email bhjelm@usc.edu if you want assistance processing data before then).

Scripts not included for steps in _NAR_ paper are pre-alignment steps (removal of PCR duplicates and adapter sequence using bbmap). See our supplemental methods section & https://jgi.doe.gov/data-and-tools/bbtools
And MapSplice 2 alignment. (see below for demos)

An example of the bbmap steps (if starting with Sample.READ1.fq and Sample.READ2.fq in your /home directory) is as follows:

bash dedupe.sh in1=/home/Sample.READ1.fq in2=/home/Sample.READ2.fq out=/home/Sample_interleaved.fq ac=f &

bash reformat.sh in=/home/Sample_interleaved.fq out1=/home/Sample.READ1.deduped.fq out2=/home/Sample.READ2.deduped.fq &  

bash bbduk.sh in1=/home/Sample.READ1.deduped.fq in2=/home/Sample.READ2.deduped.fq out=/home/Sample_interleaved2.fq ref=/som/gene/mito/FASTQ/bbmap/resources/truseq.fa &

bash reformat.sh in=/home/Sample_interleaved2.fq out1=/home/Sample.READ1.deduped.deAdapt.fq out2=/home/Sample.READ2.deduped.deAdapt.fq &

An example using these deduped.deAdapt.fq files for MapSplice 2 alignment is as follows (based on the sample_bash.sh found in http://www.netlab.uky.edu/p/bioinfo/MapSplice2) :

OUTPUT_DIR=/home/mapsplice_output
READ_FILE_END1=/home/Sample.READ1.deduped.deAdapt.fq
READ_FILE_END2=/home/Sample.READ2.deduped.deAdapt.fq
MAPSPLICE_DIR=/PATH-TO-MAPSPLICE/MapSplice-v2.1.8
REF_GENOME=/DIRECTORY_w_rCRS_FASTA/NC_012920.1

module load python/2.7.2
module load bowtie/1.0.0
module load samtools/0.1.19

echo "Starting MapSplice"
python $MAPSPLICE_DIR/mapsplice.py \
       --non-canonical \
       --qual-scale phred33 \
       -1 $READ_FILE_END1 \
       -2 $READ_FILE_END2 \
       -c $REF_GENOME \
       -p 8 \
       -o $OUTPUT_DIR 2>Sample_log.txt \
echo "Finished MapSplice"

The filtering steps that followed (removal of calls based on overhang length, distance from primers, and singletons) were done manually in Microsoft Excel, so no seperate scripts exist for these individual steps. But much of this will be included in our updated version as part of a unix wrapper.
